{
  "openapi": "3.0.0",
  "info": {
    "title": "Ordering",
    "version": "1.0",
    "description": "БАРАА ЗАХИАЛГА ХИЙХТЭЙ ХОЛБООТОЙ API-ууд\n"
  },
  "servers": [
    {
      "url": "http://localhost:3000"
    }
  ],
  "paths": {
    "/Order/EditOrder": {
      "parameters": [],
      "post": {
        "summary": "2. Edit Order",
        "operationId": "post-EditOrder",
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "description": "Захиалга засварлах",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Order"
              },
              "examples": {
                "example-1": {
                  "value": {
                    "orderId": 0,
                    "orderDate": "string",
                    "status": 0,
                    "completeDate": "string",
                    "merchantId": 0,
                    "description": "string",
                    "items": [
                      {
                        "orderId": 0,
                        "ItemId": 0,
                        "qty": 0,
                        "price": 0,
                        "complateQty": 0,
                        "cancelQty": 0,
                        "description": "string",
                        "productId": 0,
                        "supplierId": 0,
                        "supplierName": "string",
                        "productName": "string"
                      }
                    ],
                    "ExpiryDate": "string",
                    "": "string"
                  }
                }
              }
            }
          },
          "description": "Захиалга засварлах"
        }
      }
    },
    "/Order/CreateOrder": {
      "post": {
        "summary": "1. Create Order",
        "operationId": "post-user",
        "responses": {
          "200": {
            "description": "Order created",
            "content": {
              "application/json": {
                "schema": {
                  "description": "",
                  "type": "object",
                  "properties": {
                    "orderId": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "orderId"
                  ]
                },
                "examples": {}
              },
              "application/xml": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "example-1": {
                    "value": {}
                  }
                }
              }
            }
          },
          "400": {
            "description": "Missing Required Information"
          },
          "401": {
            "description": "Unauthorized"
          },
          "409": {
            "description": "Email Already Taken"
          },
          "501": {
            "description": "Not Implemented",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "merchantId": {
                    "type": "number",
                    "description": "Захилга үүсгэж байгаа байгууллага мерчантын дэлгүүрийн дугаар"
                  },
                  "description": {
                    "type": "string"
                  },
                  "items": {
                    "type": "array",
                    "items": {
                      "$ref": "#/components/schemas/OrderItems"
                    }
                  }
                },
                "required": [
                  "merchantId"
                ]
              },
              "examples": {
                "example-1": {
                  "value": {
                    "merchantId": 1,
                    "description": "",
                    "items": [
                      {
                        "orderId": 0,
                        "ItemId": 0,
                        "qty": 0,
                        "price": 0,
                        "complateQty": 0,
                        "cancelQty": 0,
                        "description": "string"
                      }
                    ]
                  }
                }
              }
            },
            "application/xml": {
              "schema": {
                "type": "object",
                "properties": {}
              }
            }
          },
          "description": "Шинэ захиалга үүсгэх"
        },
        "description": "Барааны захиалга өгөх",
        "parameters": []
      },
      "parameters": []
    },
    "/Order/DetailOrder": {
      "post": {
        "summary": "3. Detail Order",
        "operationId": "post-DetailOrder",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Order"
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "orderId": 0,
                      "orderDate": "string",
                      "status": 0,
                      "completeDate": "string",
                      "merchantId": 0,
                      "description": "string",
                      "items": [
                        {
                          "orderId": 0,
                          "ItemId": 0,
                          "qty": 0,
                          "price": 0,
                          "complateQty": 0,
                          "cancelQty": 0,
                          "description": "string"
                        }
                      ],
                      "ExpiryDate": "string"
                    }
                  }
                }
              }
            }
          }
        },
        "description": "Захиалгын мэдээлэл лавлах",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "description": "",
                "type": "object",
                "properties": {
                  "orderId": {
                    "type": "number"
                  }
                },
                "required": [
                  "orderId"
                ]
              }
            }
          },
          "description": ""
        }
      },
      "parameters": []
    },
    "/Order/CancelOrder": {
      "post": {
        "summary": "5. Cancel Order",
        "operationId": "post-CancelOrder",
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "description": "Захиалгын цуцлах",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "orderId": {
                    "type": "integer"
                  },
                  "description": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "description": ""
        }
      },
      "parameters": []
    },
    "/Order/CompleteOrder": {
      "post": {
        "summary": "4. Complete Order",
        "operationId": "post-CompleteOrder",
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Order"
              }
            }
          }
        },
        "description": "Захиалгыг амжилттай хүлээж авах"
      },
      "parameters": []
    },
    "/Order/OrderList": {
      "post": {
        "summary": "6. List order",
        "operationId": "post-OrderList",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Order"
                  }
                },
                "examples": {
                  "example-1": {
                    "value": [
                      {
                        "orderId": 0,
                        "orderDate": "string",
                        "status": 0,
                        "completeDate": "string",
                        "merchantId": 0,
                        "description": "string",
                        "items": [
                          {
                            "orderId": 0,
                            "ItemId": 0,
                            "qty": 0,
                            "price": 0,
                            "complateQty": 0,
                            "cancelQty": 0,
                            "description": "string"
                          }
                        ],
                        "ExpiryDate": "string"
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "limit": {
                    "type": "integer",
                    "minimum": 10
                  },
                  "offset": {
                    "type": "integer",
                    "minimum": 1
                  },
                  "sortBy": {
                    "type": "string",
                    "example": "orderDate, supplierId"
                  },
                  "filters": {
                    "type": "array",
                    "items": {
                      "$ref": "#/components/schemas/Filter"
                    }
                  }
                }
              },
              "examples": {
                "example-1": {
                  "value": {
                    "limit": 10,
                    "offset": 1,
                    "sortBy": "orderDate, supplierId",
                    "filters": [
                      {
                        "field": "string",
                        "operation": "=",
                        "type": "number",
                        "value": "string"
                      }
                    ]
                  }
                }
              }
            }
          },
          "description": ""
        },
        "description": "Захиалгын жагсаалт авах"
      },
      "parameters": []
    },
    "/Auth/Login": {
      "post": {
        "summary": "Login",
        "operationId": "post-Login",
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              }
            }
          },
          "description": ""
        },
        "description": "SCOPA систем руу нэвтрэх"
      },
      "parameters": []
    },
    "/Supply/ProductBalance": {
      "post": {
        "summary": "Balance of product",
        "operationId": "post-ProductList",
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "description": "Дэлгүүрийн барааны үлдэгдэл",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/ProductBalance"
                }
              },
              "examples": {
                "example-1": {
                  "value": [
                    {
                      "productId": 0,
                      "name": "string",
                      "price": 0,
                      "AvailableQty": 0,
                      "catId": 0,
                      "catName": "string",
                      "supplierId": 0,
                      "supplierName": "string"
                    }
                  ]
                }
              }
            }
          }
        }
      },
      "parameters": []
    },
    "/Product/Product": {
      "post": {
        "summary": "List of products",
        "operationId": "post-Product-ProductList",
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "description": "Барааны жагсаалт",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/Product"
                }
              },
              "examples": {
                "example-1": {
                  "value": [
                    {
                      "productCode": "string",
                      "Name": "string",
                      "catId": 0,
                      "Description": "string",
                      "supplierId": 0
                    }
                  ]
                }
              }
            }
          }
        }
      },
      "parameters": []
    },
    "/Product/Category": {
      "post": {
        "summary": "List of product category",
        "operationId": "post-Product-Category",
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "description": "Барааны категорийн жагсаалт",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/Category"
                }
              },
              "examples": {
                "example-1": {
                  "value": [
                    {
                      "catId": 0,
                      "name": "string",
                      "parentCatId": 0
                    }
                  ]
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "OrderItems": {
        "title": "OrderItems",
        "type": "object",
        "description": "Захиалгын бараанууд",
        "x-examples": {
          "example-1": {
            "orderId": 0,
            "ItemId": 0,
            "qty": 0,
            "price": 0,
            "complateQty": 0,
            "cancelQty": 0,
            "description": "string"
          }
        },
        "properties": {
          "orderId": {
            "type": "integer",
            "description": "Шинэ захиалга дээр хоосон байна."
          },
          "ItemId": {
            "type": "integer",
            "description": "Захиалга доторх дэд дугаарлалт"
          },
          "qty": {
            "type": "number",
            "description": "Захиалах тоо"
          },
          "price": {
            "type": "number",
            "format": "double",
            "description": "Барааны үнэ"
          },
          "complateQty": {
            "type": "number",
            "description": "Захиалга биелсэн тоо"
          },
          "cancelQty": {
            "type": "number",
            "description": "Захиалгаар хүлээж аваагүй тоо"
          },
          "description": {
            "type": "string"
          },
          "productId": {
            "type": "integer",
            "description": "Захилсан барааны код"
          },
          "supplierId": {
            "description": "Захиалсан барааны нийлүүлэгч. Олон нийлүүлэгчтэй үед ашиглана.",
            "type": "integer"
          },
          "supplierName": {
            "type": "string"
          },
          "productName": {
            "type": "string"
          }
        },
        "required": [
          "ItemId",
          "qty",
          "price"
        ]
      },
      "Order": {
        "title": "Order",
        "type": "object",
        "x-examples": {
          "example-1": {
            "orderId": "string",
            "orderDate": "string",
            "status": 0,
            "completeDate": "string",
            "merchantId": 0,
            "description": "string",
            "items": [
              {
                "orderId": 0,
                "ItemId": 0,
                "qty": 0,
                "price": 0,
                "complateQty": 0,
                "cancelQty": 0,
                "description": "string"
              }
            ]
          }
        },
        "properties": {
          "orderId": {
            "type": "integer",
            "description": "Захиалгын дугаар"
          },
          "orderDate": {
            "type": "string"
          },
          "status": {
            "type": "number"
          },
          "completeDate": {
            "type": "string"
          },
          "merchantId": {
            "type": "number"
          },
          "description": {
            "type": "string"
          },
          "items": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/OrderItems"
            }
          },
          "ExpiryDate": {
            "type": "string"
          },
          "": {
            "type": "string"
          }
        }
      },
      "Product": {
        "title": "Product",
        "type": "object",
        "properties": {
          "productCode": {
            "type": "string"
          },
          "Name": {
            "type": "string"
          },
          "catId": {
            "type": "integer"
          },
          "Description": {
            "type": "string"
          },
          "supplierId": {
            "type": "integer"
          },
          "catName": {
            "type": "string"
          },
          "supplierName": {
            "type": "string"
          }
        },
        "description": "Барааны мэдээлэл"
      },
      "Supplier": {
        "title": "Supplier",
        "type": "object",
        "properties": {
          "supplierId": {
            "type": "integer"
          },
          "Name": {
            "type": "string"
          },
          "categorys": {
            "type": "array",
            "description": "Бэлтгэн нийлүүэгчийн барааны ангилал",
            "items": {
              "type": "integer"
            }
          }
        }
      },
      "Category": {
        "title": "Category",
        "type": "object",
        "description": "Барааны ангилал",
        "properties": {
          "catId": {
            "type": "integer",
            "description": "Барааны ангилал"
          },
          "name": {
            "type": "string",
            "description": "Ангилалын нэр"
          },
          "parentCatId": {
            "type": "integer",
            "description": "Үндсэн ангилал"
          }
        }
      },
      "ProductBalance": {
        "title": "ProductBalance",
        "type": "object",
        "properties": {
          "productId": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "price": {
            "type": "number"
          },
          "AvailableQty": {
            "type": "number"
          },
          "catId": {
            "type": "integer"
          },
          "catName": {
            "type": "string"
          },
          "supplierId": {
            "type": "integer"
          },
          "supplierName": {
            "type": "string"
          }
        }
      },
      "Filter": {
        "title": "Filter",
        "type": "object",
        "description": "",
        "properties": {
          "field": {
            "type": "string"
          },
          "operation": {
            "type": "string",
            "enum": [
              "=",
              "!=",
              ">",
              ">=",
              "<",
              "<="
            ]
          },
          "type": {
            "type": "string",
            "enum": [
              "number",
              "string",
              "date"
            ]
          },
          "value": {
            "type": "string"
          }
        }
      }
    },
    "securitySchemes": {
      "NesSession": {
        "name": "API Key",
        "type": "apiKey",
        "in": "query"
      }
    }
  },
  "security": []
}