{
  "openapi": "3.0.0",
  "info": {
    "title": "Sales",
    "version": "1.0",
    "description": "БОРЛУУЛАЛТЫН МЭДЭЭЛЭЛ ХҮЛЭЭН АВАХ API-ууд"
  },
  "servers": [
    {
      "url": "http://merchant.scopa.mn"
    }
  ],
  "paths": {
    "/sales/sendSalesInfo": {
      "parameters": [],
      "post": {
        "summary": "Send sales info",
        "operationId": "19003000",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "./System.v1.json#/components/schemas/response"
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "responseCode": "string",
                      "responseDesc": "string",
                      "responseData": {}
                    }
                  }
                }
              }
            }
          }
        },
        "description": "Борлуулалтын мэдээлэл илгээх",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Sales"
              },
              "examples": {
                "example-1": {
                  "value": {
                    "id": "100011",
                    "totalPrice": 35200,
                    "payType": "CARD",
                    "salesDate": "2021.05.20 18:25",
                    "items": [
                      {
                        "prodCode": "789",
                        "prodName": "Атар талх",
                        "qty": 2,
                        "price": 1200,
                        "prodCodeBase": "111"
                      },
                      {
                        "prodCode": "856",
                        "prodName": "Eden архи",
                        "qty": 1,
                        "price": 32800,
                        "prodCodeBase": "511"
                      }
                    ]
                  }
                },
                "example-2": {
                  "value": {
                    "merchantId": "string",
                    "branchNo": "string",
                    "posNo": "string",
                    "districtCode": "string",
                    "customerNo": "string",
                    "billType": "string",
                    "billIdSuffix": "string",
                    "invoiceId": "string",
                    "amount": "string",
                    "cashAmount": "string",
                    "nonCashAmount": "string",
                    "vat": "string",
                    "cityTax": "string",
                    "returnBillId": "string",
                    "taxType": "string",
                    "stocks": [
                      {
                        "productCode": "string",
                        "code": "string",
                        "name": "string",
                        "measureUnit": "string",
                        "qty": "string",
                        "unitPrice": "string",
                        "totalAmount": "string",
                        "cityTax": "string",
                        "vat": "string",
                        "barCode": "string",
                        "supplierId": "string",
                        "supplierName": "string",
                        "serialNo": "string",
                        "SKU": "string"
                      }
                    ],
                    "bankTransactions": [
                      {
                        "rrn": "string",
                        "bankId": "string",
                        "terminalId": "string",
                        "approvalCode": "string",
                        "amount": "string",
                        "curCode": "MNT"
                      }
                    ],
                    "group": true,
                    "reportMonth": "string",
                    "saleId": "string",
                    "saleDate": "string"
                  }
                }
              }
            }
          },
          "description": "Борлуулалтын мэдээлэл"
        },
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "header",
            "name": "SessionToken",
            "description": "Connect функцээр авсан TOKEN",
            "required": true
          }
        ]
      }
    },
    "/sales/sendSalesInfoBatch": {
      "post": {
        "summary": "Send sales info batch",
        "operationId": "post-sales-sendSalesInfoBatch",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "./System.v1.json#/components/schemas/response"
                }
              }
            }
          },
          "501": {
            "description": "Not Implemented"
          }
        },
        "description": "Багцаар борлуулалтын мэдээлэл илгээх",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/Sales"
                }
              },
              "examples": {
                "example-1": {
                  "value": [
                    {
                      "id": "100010",
                      "totalPrice": 230,
                      "payType": "CARD",
                      "salesDate": "2021.05.20 18:25",
                      "items": [
                        {
                          "prodCode": "123",
                          "prodName": "Талх",
                          "qty": 1,
                          "price": 230,
                          "prodCodeBase": "1250"
                        }
                      ]
                    },
                    {
                      "id": "100011",
                      "totalPrice": 2780,
                      "payType": "CASH",
                      "salesDate": "2021.05.20 18:23",
                      "items": [
                        {
                          "prodCode": "7778",
                          "prodName": "Гоймон",
                          "qty": 1,
                          "price": 2780,
                          "prodCodeBase": "452"
                        }
                      ]
                    }
                  ]
                },
                "example-2": {
                  "value": [
                    {
                      "merchantId": "M1001",
                      "branchNo": "B001",
                      "posNo": "001",
                      "districtCode": "string",
                      "customerNo": "string",
                      "billType": "string",
                      "billIdSuffix": "string",
                      "invoiceId": "string",
                      "amount": "string",
                      "cashAmount": "string",
                      "nonCashAmount": "string",
                      "vat": "string",
                      "cityTax": "string",
                      "returnBillId": "string",
                      "taxType": "string",
                      "stocks": [
                        {
                          "productCode": "string",
                          "code": "string",
                          "name": "string",
                          "measureUnit": "string",
                          "qty": "string",
                          "unitPrice": "string",
                          "totalAmount": "string",
                          "cityTax": "string",
                          "vat": "string",
                          "barCode": "string",
                          "supplierId": "string",
                          "supplierName": "string",
                          "serialNo": "string",
                          "SKU": "string"
                        }
                      ],
                      "bankTransactions": [
                        {
                          "rrn": "string",
                          "bankId": "string",
                          "terminalId": "string",
                          "approvalCode": "string",
                          "amount": "string",
                          "curCode": "MNT"
                        }
                      ],
                      "group": true,
                      "reportMonth": "string",
                      "saleId": "string",
                      "saleDate": "string"
                    }
                  ]
                }
              }
            }
          },
          "description": "Нэг хүсэлт дотор 50-с илүүгүй борлуулалтын мэдээг багцалж илгээнэ."
        },
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "header",
            "name": "SessionToken",
            "description": "Connect функцээр авсан TOKEN",
            "required": true
          }
        ]
      }
    },
    "/sales/sendReverseInfo": {
      "post": {
        "summary": "Send sales reversal info",
        "operationId": "post-sales-sendReverseInfo",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "./System.v1.json#/components/schemas/response"
                }
              }
            }
          }
        },
        "description": "Буцаалтын гүйлгээний мэдээ илгээх",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Sales"
              },
              "examples": {
                "example-1": {
                  "value": [
                    {
                      "id": "string",
                      "prodCode": "string",
                      "prodName": "string",
                      "qty": 0,
                      "price": 0,
                      "prodCodeBase": "string"
                    },
                    {
                      "id": "string",
                      "prodCode": "string",
                      "prodName": "string",
                      "qty": 0,
                      "price": 0,
                      "prodCodeBase": "string"
                    }
                  ]
                },
                "example-2": {
                  "value": {
                    "merchantId": "string",
                    "branchNo": "string",
                    "posNo": "string",
                    "districtCode": "string",
                    "customerNo": "string",
                    "billType": "string",
                    "billIdSuffix": "string",
                    "invoiceId": "string",
                    "amount": "string",
                    "cashAmount": "string",
                    "nonCashAmount": "string",
                    "vat": "string",
                    "cityTax": "string",
                    "returnBillId": "string",
                    "taxType": "string",
                    "stocks": [
                      {
                        "productCode": "string",
                        "code": "string",
                        "name": "string",
                        "measureUnit": "string",
                        "qty": "string",
                        "unitPrice": "string",
                        "totalAmount": "string",
                        "cityTax": "string",
                        "vat": "string",
                        "barCode": "string",
                        "supplierId": "string",
                        "supplierName": "string",
                        "serialNo": "string",
                        "SKU": "string"
                      }
                    ],
                    "bankTransactions": [
                      {
                        "rrn": "string",
                        "bankId": "string",
                        "terminalId": "string",
                        "approvalCode": "string",
                        "amount": "string",
                        "curCode": "MNT"
                      }
                    ],
                    "group": true,
                    "reportMonth": "string",
                    "saleId": "string",
                    "saleDate": "string"
                  }
                }
              }
            }
          },
          "description": "Буцааж байгаа бараанууд"
        },
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "header",
            "name": "SessionToken",
            "description": "Connect функцээр авсан TOKEN",
            "required": true
          }
        ]
      }
    },
    "/inv/sendProdBal": {
      "post": {
        "summary": "Send product balance",
        "operationId": "post-inv-sendProdBal",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "./System.v1.json#/components/schemas/response"
                }
              }
            }
          }
        },
        "description": "Барааны үлдэгдэл дамжуулах",
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "header",
            "description": "Connect функцээр авсан TOKEN",
            "name": "SessionToken"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/Product"
                }
              },
              "examples": {
                "example-1": {
                  "value": [
                    {
                      "prodCode": "string",
                      "prodName": "string",
                      "prodCodeBase": "string",
                      "qty": 0,
                      "unit": "string",
                      "supplierName": "string",
                      "supplierId": "string",
                      "catId": "string",
                      "catName": "string"
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/Order/DetailOrder": {
      "post": {
        "summary": "Detail Order",
        "operationId": "19001004",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "./Order.json#/components/schemas/Order"
                },
                "examples": {
                  "Захиалга 12": {
                    "value": {
                      "orderId": 12,
                      "orderDate": "2021.03.12",
                      "status": 0,
                      "statusName": "Хүлээгдэж байгаа",
                      "merchantId": 123,
                      "description": "Атар талх 10, Боов-10",
                      "expiryDate": "2021.03.30",
                      "totalPrice": 45000,
                      "payType": "LINE",
                      "payAmount": 45000,
                      "curCode": "MNT",
                      "items": [
                        {
                          "ItemId": 1,
                          "productCode": "AT001",
                          "productName": "Атар талх",
                          "qty": 10,
                          "meas": "C",
                          "price": 1500,
                          "curCode": "MNT",
                          "supplierId": 123,
                          "description": "Талх"
                        },
                        {
                          "ItemId": 2,
                          "productCode": "AT002",
                          "productName": "Боорцог",
                          "qty": 10,
                          "meas": "C",
                          "price": 3000,
                          "curCode": "MNT",
                          "supplierId": 123,
                          "description": ""
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "501": {
            "$ref": "#/components/responses/501"
          }
        },
        "description": "Захиалгын мэдээлэл лавлах",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "description": "Захалга",
                "type": "object",
                "properties": {
                  "orderId": {
                    "type": "number",
                    "description": "Захиалгын дугаар"
                  }
                },
                "required": [
                  "orderId"
                ]
              },
              "examples": {
                "Захиалга 12": {
                  "value": {
                    "orderId": 12
                  }
                }
              }
            }
          },
          "description": ""
        }
      },
      "parameters": []
    }
  },
  "components": {
    "schemas": {
      "SalesItem_old": {
        "description": "Борлуулалт доторх барааны мэдээлэл",
        "type": "object",
        "properties": {
          "prodCode": {
            "type": "string",
            "minLength": 1,
            "description": "Барааны ID дэлгүүр дотроо ашигладаг код"
          },
          "prodName": {
            "type": "string",
            "minLength": 1,
            "description": "Барааны нэр"
          },
          "qty": {
            "type": "number",
            "description": "Тоо хэмжээ"
          },
          "price": {
            "type": "number",
            "description": "Үнэ"
          },
          "prodCodeBase": {
            "type": "string",
            "description": "Барааны Scopa дээрх код. "
          }
        },
        "required": [
          "prodCode",
          "prodName",
          "qty",
          "price"
        ]
      },
      "Sales_old": {
        "title": "Sales_old",
        "type": "object",
        "description": "Борлуулалтын мэдээ",
        "x-examples": {
          "example-1": {
            "id": "string",
            "totalPrice": 0,
            "payType": "string",
            "salesDate": "2021.05.20 18:25",
            "items": [
              {
                "prodCode": "string",
                "prodName": "string",
                "qty": 0,
                "price": 0,
                "prodTag": "string"
              }
            ]
          }
        },
        "properties": {
          "id": {
            "type": "string",
            "description": "Борлуулалтын давтагдахгүй дугаарлалт"
          },
          "totalPrice": {
            "type": "number"
          },
          "payType": {
            "type": "string",
            "description": "Төлбөр хийсэн хэлбэр, CASH, CARD, MOBILE, MIXED"
          },
          "salesDate": {
            "type": "string",
            "description": "борлуулалт хийсэн огноо, цаг, минуттай",
            "format": "date-time",
            "example": "2021.05.20 18:25",
            "default": "yyyy.MM.dd hh:mi"
          },
          "items": {
            "type": "array",
            "description": "Борлуулсан бараанууд",
            "items": {
              "$ref": "#/components/schemas/SalesItem_old"
            }
          }
        },
        "required": [
          "id",
          "totalPrice"
        ]
      },
      "OrderItems": {
        "title": "OrderItems",
        "type": "object",
        "description": "Захиалгын бараанууд",
        "x-examples": {},
        "properties": {
          "orderId": {
            "type": "integer",
            "description": "Захиалгын дугаар"
          },
          "itemId": {
            "type": "integer",
            "description": "Захиалгын дэд дугаар"
          },
          "qty": {
            "type": "number",
            "description": "Захиалах тоо",
            "format": "double"
          },
          "price": {
            "type": "number",
            "format": "double",
            "description": "Барааны үнэ"
          },
          "complateQty": {
            "type": "number",
            "description": "Захиалгаар хүлээн авсан тоо",
            "format": "double"
          },
          "cancelQty": {
            "type": "number",
            "description": "Захиалгаар хүлээж аваагүй тоо"
          },
          "description": {
            "type": "string",
            "description": "Нэмэлт тайлбар"
          },
          "productCode": {
            "description": "Барааны код",
            "type": "string"
          },
          "supplierId": {
            "description": "Захиалсан барааны нийлүүлэгч. Олон нийлүүлэгчтэй үед ашиглана.",
            "type": "integer"
          },
          "supplierName": {
            "type": "string",
            "description": "Нийлүүлэгчийн нэр"
          },
          "productName": {
            "type": "string",
            "description": "Барааны нэр"
          },
          "curCode": {
            "type": "string",
            "description": "Валют"
          },
          "measureUnit": {
            "type": "string",
            "description": "Хэмжих нэгж: C - ширхэг, Kg - kilogram, L - liter  "
          }
        },
        "required": [
          "itemId",
          "qty",
          "price"
        ]
      },
      "Order": {
        "title": "Order",
        "type": "object",
        "x-examples": {},
        "description": "Захиалгын мэдээлэл",
        "properties": {
          "orderId": {
            "type": "integer",
            "description": "Захиалгын дугаар"
          },
          "orderDate": {
            "type": "string",
            "description": "Захиалгын огноо"
          },
          "status": {
            "type": "number",
            "description": "Төлөв"
          },
          "completeDate": {
            "type": "string",
            "description": "Захиалга биелсэн огноо"
          },
          "merchantId": {
            "type": "number",
            "description": "Дэлгүүрийн дугаар"
          },
          "description": {
            "type": "string",
            "description": "Захиалгын ерөнхий утга"
          },
          "expiryDate": {
            "type": "string",
            "description": "Захиалгын хүчинтэй хугацаа"
          },
          "totalPrice": {
            "type": "number",
            "description": "Захиалгын нийт үнэ"
          },
          "statusName": {
            "type": "string",
            "description": "Төлөвийн нэр"
          },
          "items": {
            "type": "array",
            "description": "Захиалгын бараанууд",
            "items": {
              "$ref": "#/components/schemas/OrderItems"
            }
          },
          "payType": {
            "type": "string",
            "description": "Төлбөрийн хэлбэр CASH, LINE"
          },
          "curCode": {
            "type": "string",
            "description": "Валют",
            "example": "MNT"
          },
          "payAmount": {
            "type": "number"
          },
          "branchNo": {
            "type": "string"
          }
        }
      },
      "ReversalItem": {
        "title": "ReversalItem",
        "type": "object",
        "description": "Буцаалт доторх барааны мэдээлэл",
        "properties": {
          "id": {
            "type": "string",
            "description": "Борлуулалтын дугаар"
          },
          "prodCode": {
            "type": "string",
            "description": "Барааны код"
          },
          "prodName": {
            "type": "string",
            "description": "Барааны нэр"
          },
          "qty": {
            "type": "number",
            "description": "Тоо ширхэг"
          },
          "unitPrice": {
            "type": "number",
            "description": "нэгж үнэ"
          },
          "productCode": {
            "type": "string",
            "description": "Барааны код Скопа платформ дээрх"
          }
        },
        "required": [
          "id",
          "prodCode",
          "prodName",
          "qty",
          "unitPrice"
        ]
      },
      "Product": {
        "title": "Product",
        "type": "object",
        "description": "Барааны мэдээлэл",
        "properties": {
          "prodCode": {
            "type": "string"
          },
          "prodName": {
            "type": "string"
          },
          "productCode": {
            "type": "string",
            "description": "Барааны Scopa дээрх код. "
          },
          "qty": {
            "type": "number",
            "description": "Үлдэгдэл"
          },
          "unitPrice": {
            "type": "string",
            "description": "Хэмжих нэгж"
          },
          "supplierName": {
            "type": "string",
            "description": "Нийлүүлэгчийн нэр"
          },
          "supplierId": {
            "type": "string",
            "description": "Нийлүүлэгчийн Id"
          },
          "catId": {
            "type": "string",
            "description": "Категори id"
          },
          "catName": {
            "type": "string",
            "description": "Категори нэр"
          }
        },
        "required": [
          "prodCode",
          "prodName",
          "qty",
          "unitPrice"
        ]
      },
      "SalesItem": {
        "title": "SalesItem",
        "type": "object",
        "description": "Борлуулалт доторх барааны мэдээлэл",
        "properties": {
          "productCode": {
            "type": "string",
            "description": "SCOPA-н барааны код"
          },
          "code": {
            "type": "string",
            "description": "Өөрийн систем дээрх барааны код"
          },
          "name": {
            "type": "string",
            "description": "Барааны нэр"
          },
          "measureUnit": {
            "type": "string",
            "description": "Хэмжих нэгж"
          },
          "qty": {
            "type": "string",
            "description": "2 орны нарийвчлалтай тоо Тоо, хэмжээ"
          },
          "unitPrice": {
            "type": "string",
            "description": "2 орны нарийвчлалтай тоо Нэгж үнэ Бүх төрлийн татвар шингэсэн дүн"
          },
          "totalAmount": {
            "type": "string",
            "description": "Нийт үнэ"
          },
          "cityTax": {
            "type": "string",
            "description": "Хотын татвар"
          },
          "vat": {
            "type": "string",
            "description": "Татвар"
          },
          "barCode": {
            "type": "string",
            "description": "Барааны баркод"
          },
          "supplierId": {
            "type": "string",
            "description": "Нийлүүлэгч дугаар"
          },
          "supplierName": {
            "type": "string",
            "description": "Нийлүүлэгч"
          },
          "serialNo": {
            "type": "string"
          },
          "SKU": {
            "type": "string",
            "description": "Stock Keeping Units (SKUs)"
          },
          "ItemId": {
            "type": "number",
            "description": "Борлуулалтын дэд дугаар"
          },
          "returnItemId": {
            "type": "number",
            "description": "Буцаасан борлуулалтын дэд дугаар"
          }
        },
        "required": [
          "productCode",
          "measureUnit",
          "qty",
          "unitPrice",
          "totalAmount"
        ]
      },
      "Sales": {
        "title": "Sales",
        "type": "object",
        "description": "Борлуулалтын мэдээ",
        "x-internal": false,
        "x-examples": {},
        "properties": {
          "merchantId": {
            "type": "string"
          },
          "branchNo": {
            "type": "string"
          },
          "posNo": {
            "type": "string"
          },
          "districtCode": {
            "type": "string"
          },
          "customerNo": {
            "type": "string"
          },
          "billType": {
            "type": "string",
            "description": "Төлбөр хийсэн хэлбэр: CASH, CARD, MOBILE, MIXED"
          },
          "billIdSuffix": {
            "type": "string"
          },
          "invoiceId": {
            "type": "string"
          },
          "amount": {
            "type": "string"
          },
          "cashAmount": {
            "type": "string"
          },
          "nonCashAmount": {
            "type": "string"
          },
          "vat": {
            "type": "string"
          },
          "cityTax": {
            "type": "string"
          },
          "returnSalesId": {
            "type": "string"
          },
          "taxType": {
            "type": "string"
          },
          "stocks": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/SalesItem"
            }
          },
          "fp": {
            "type": "string"
          },
          "salesId": {
            "type": "string",
            "description": "Борлуулалтын давтагдахгүй дугаарлалт"
          },
          "salesDate": {
            "type": "string",
            "description": "борлуулалт хийсэн огноо, цаг, минуттай"
          },
          "returnDate": {
            "type": "string",
            "description": "Буцаалт хийсэн огноо"
          }
        }
      },
      "SalesTransaction": {
        "title": "BillBankTransaction",
        "type": "object",
        "properties": {
          "rrn": {
            "type": "string",
            "description": "12 оронтой бүхэл тоо Бэлэн бус гүйлгээний баримтын дугаар\n"
          },
          "bankId": {
            "type": "string",
            "description": "2 оронтой бүхэл тоо Пос терминалын эзэмшигч банкны код"
          },
          "terminalId": {
            "type": "string",
            "description": "Латин үсэг тоо холилдсон 6 ба түүнээс дээш тэмдэгт бүхий тэмдэгт мөр Пос терминалын дугаар"
          },
          "approvalCode": {
            "type": "string"
          },
          "amount": {
            "type": "string",
            "description": "Дүн"
          },
          "curCode": {
            "type": "string",
            "description": "Валют",
            "default": "MNT",
            "minLength": 3,
            "maxLength": 3
          }
        }
      }
    }
  }
}