{
  "openapi": "3.0.0",
  "info": {
    "title": "System",
    "version": "1.0",
    "description": "System холболт тогтоох, холболт шалгах зэрэг апи функцүүд",
    "contact": {
      "name": "",
      "email": "scopa@scopa.mn"
    }
  },
  "servers": [
    {
      "url": "https://merchant.scopa.mn"
    }
  ],
  "paths": {
    "/echo": {
      "parameters": [],
      "get": {
        "summary": "echo",
        "operationId": "16200001",
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "description": "Холболт хэвийн байгаа эсэхийг шалгана",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "default": "8aPsc1XMdwor3kS3spYOFDSqNmq4vd"
            },
            "in": "header",
            "name": "SessionToken"
          }
        ]
      }
    },
    "/connectMerch": {
      "parameters": [],
      "post": {
        "summary": "Connect",
        "operationId": "16200002",
        "responses": {
          "200": {
            "description": "Энэ токенийг ашиглана дараа дараачийн үйлдлүүдийг хийнэ",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/connect_response"
                }
              }
            }
          },
          "500": {
            "description": "41000225 - Системд нэвтрээгүй байна"
          },
          "501": {
            "description": "Session үүсгэж өгөх боломжгүй ",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/connect_response"
                },
                "examples": {
                  "TAN code expired": {
                    "value": {
                      "responseCode": 2,
                      "responseDesc": "TAN code expired!",
                      "responseData": null,
                      "merchantId": null,
                      "merchantName": null,
                      "sessionToken": null
                    }
                  }
                }
              }
            }
          }
        },
        "description": "СКОПА платформд холболт тогтоох. ",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "string",
                "example": "413799",
                "description": "Тан код"
              },
              "examples": {
                "Default": {
                  "value": "413799"
                }
              }
            },
            "application/xml": {
              "schema": {
                "type": "object",
                "properties": {}
              }
            }
          },
          "description": "Холболтын session token авах функц. Авсан токеноо ашиглана дараа дараачийн үйлдлүүдийг хийнэ."
        },
        "parameters": []
      }
    },
    "/getCommand": {
      "parameters": [],
      "post": {
        "summary": "getCommand",
        "operationId": "16200003",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/response"
                },
                "examples": {
                  "orderComplate": {
                    "value": {
                      "responseCode": 0,
                      "responseDesc": "Амжилттай",
                      "responseData": "",
                      "cmd": "TAKE_ORDER_DATA",
                      "data": "1200012"
                    }
                  },
                  "To send inv balance": {
                    "value": {
                      "responseCode": 0,
                      "responseDesc": "Амжилттай",
                      "responseData": "",
                      "cmd": "SEND_PROD_BAL",
                      "data": "1245"
                    }
                  }
                }
              }
            }
          }
        },
        "description": "Системээс өгсөн командыг авах. ",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "default": "8aPsc1XMdwor3kS3spYOFDSqNmq4vd"
            },
            "in": "header",
            "name": "SessionToken"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "integer",
                "default": 1
              },
              "examples": {
                "Merchant": {
                  "value": 1
                }
              }
            }
          },
          "description": "Мерчантын дугаар"
        }
      }
    }
  },
  "components": {
    "schemas": {
      "response": {
        "description": "",
        "type": "object",
        "properties": {
          "responseCode": {
            "type": "number"
          },
          "responseDesc": {
            "type": "string"
          },
          "responseData": {},
          "cmd": {
            "type": "string"
          },
          "data": {
            "type": "string"
          }
        },
        "required": [
          "responseCode",
          "responseDesc",
          "cmd",
          "data"
        ],
        "x-examples": {}
      },
      "connect_response": {
        "description": "",
        "type": "object",
        "properties": {
          "responseCode": {
            "type": "number"
          },
          "responseDesc": {
            "type": "string",
            "minLength": 1
          },
          "responseData": {},
          "merchantId": {},
          "merchantName": {},
          "sessionToken": {}
        },
        "required": [
          "responseCode",
          "responseDesc"
        ],
        "x-examples": {
          "ConnectedMerchant": {
            "value": {
              "responseCode": 0,
              "responseDesc": "",
              "responseData": null,
              "merchantId": 1,
              "merchantName": "Цэцэг дэлгүүр",
              "sessionToken": "ыбсыбсыбөыбөмыбө"
            }
          }
        }
      }
    },
    "responses": {}
  }
}